[package]
name = "hextui"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A minimal hex file viewer"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
hex = "0.4.3"
ratatui = "0.30.0"
